---
- name: Instal Nginx di CentOS 7
  hosts: all  # Ganti dengan nama host atau grup host Anda
  become: yes  # Menggunakan privilege escalation untuk menjadi root
  tasks:
   - name: Instal Nginx
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"
