---
- name: Instal Apache HTTP Server (httpd) di CentOS
  hosts: all
  become: yes
  tasks:
    - name: Perbarui cache paket
      yum:
        name: '*'
        state: latest
      register: update_cache

    - name: Instal httpd (Apache)
      yum:
        name: httpd
        state: present
      when: "'httpd' not in update_cache.failed"

    - name: Mulai dan aktifkan layanan httpd
      service:
        name: httpd
        state: started
        enabled: yes
