---
- name: Instal Nginx di CentOS 7
  hosts: all  # Ganti dengan nama host atau grup host Anda
  become: yes  # Menggunakan privilege escalation untuk menjadi root
  tasks:
    - name: Update cache paket
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Instal Nginx
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start Nginx
      systemd:
        name: nginx
        state: started
      when: ansible_os_family == "RedHat"
      
    - name: Enable Nginx di boot
      systemd:
        name: nginx
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Allow HTTP di firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
      when: ansible_os_family == "RedHat"
      
    - name: Reload firewall
      command: firewall-cmd --reload
      when: ansible_os_family == "RedHat"
