---
- name: Install Nginx and Configure app.conf
- hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
    
    - name: Create conf.d folder
      file:
        path: /etc/nginx/conf.d
        state: directory

    - name: Create app.conf file
      copy:
        content: |
          upstream backend {
            least_conn;
            server 192.168.5.32; #node1
            server 192.168.5.33; #node2
          }

          server {
            listen 80;
            server_name apps.sentralpinjaman.co.id;
            return 301 https://apps.sentralpinjaman.co.id$request_uri;
          }

          server {
            listen 443 ssl;
            server_name apps.sentralpinjaman.co.id;
            ssl_certificate /etc/ssl/certs/ssl-bundle.crt;
            ssl_certificate_key /etc/ssl/certs/commercial.key;
            ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
            ssl_ciphers HIGH:!aNULL:!MD5;

            location / {
              proxy_redirect off;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $http_host;
              proxy_pass http://backend;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
          }
        dest: /etc/nginx/conf.d/app.conf
