---
- name: Restart Nginx on CentOS
  hosts: all
  become: yes
  tasks:
    - name: Restart Nginx Service on CentOS
      systemd:
        name: nginx
        state: restarted
      when: ansible_distribution == "CentOS"
