---
- name: Instal Nginx di CentOS 7
  hosts: web-servers
  become: yes  # Menggunakan privilege escalation untuk menjadi root
  tasks:
     - name: Instal Nginx
      yum:
        name: nginx
        state: present
     

    - name: Start Nginx
      systemd:
        name: nginx
        state: started
      
      
    - name: Enable Nginx di boot
      systemd:
        name: nginx
        enabled: yes
        
