---
- name: Install Nginx on CentOS 7
  hosts: all
  become: yes

  tasks:
    - name: Update the package cache
      yum:
        name: "*"
        state: latest
      tags:
        - update

    - name: Install Nginx
      yum:
        name: nginx
        state: present
      tags:
        - install

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - start

    - name: Allow Nginx through the firewall
      firewalld:
        service: http
        state: enabled
        permanent: yes
      tags:
        - firewall
