---
- name: web configuration
  hosts: all 
  gather_facts: false
  become: true# yum -y install httpd 
    - name: httpd installation
      yum:
        name: httpd
        state: present

# systemctl start httpd && systemctl enable httpd 
    - name: httpd start and enable
      service:
        name: httpd
        state: started
        enabled: true
