---
- name: Install Nginx
  hosts: web-servers
  become: yes
  tasks:
    - name: Update package cache
      yum:
        name: '*'
        state: latest
      tags:
        - update

    - name: Install Nginx
      yum:
        name: nginx
        state: present
      tags:
        - nginx

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - nginx

    - name: Allow HTTP traffic through firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
      tags:
        - firewall

    - name: Reload Firewall
      firewalld:
        permanent: yes
        state: reloaded
      tags:
        - firewall
