---
- name: Install Nginx on CentOS 7
  hosts: all  # Ganti dengan nama host atau grup host Anda
  become: yes  # Untuk memungkinkan perintah sudo

  tasks:
    - name: Update package cache
      yum:
        name: '*'
        state: latest
      become: yes

    - name: Install Nginx
      yum:
        name: nginx
        state: present
      become: yes

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      become: yes
