---
- name: Instal wget di CentOS 7
  hosts: all  # Ganti dengan nama atau alamat IP server target Anda
  become: yes  # Untuk mendapatkan izin root

  tasks:
    - name: Instal wget
      yum:
        name: wget
        state: present
