---
- name: web configuration
  hosts: all 
  gather_facts: false
  become: true

  tasks:
# yum -y install libselinux-python 
    - name: libselinux-python installation
      yum:
        name: libselinux-python
        state: present

# yum -y install epel-release
    - name: epel-release installation
      yum:
        name: epel-release
        state: present

# yum -y install nginx  
    - name: nginx installation
      yum:
        name: nginx
        state: present

# systemctl start nginx && systemctl enable nginx 
    - name: nginx start and enable
      service:
        name: nginx
        state: started
        enabled: true
